language: csharp
mono:
  - 5.12.0
solution: B9PartSwitch.sln
before_install:
  - sudo apt-get install python3-pip python3-setuptools
install:
  - rvm install $(cat .ruby-version)
  - bundle install
  - pip3 install awscli --upgrade --user
  - install-ksp-dlls
  - nuget restore ${TRAVIS_SOLUTION}
script:
  - bundle exec rubocop
  - msbuild /p:Configuration=Release /p:ReferencePath="${KSP_DLL_PATH}" ${TRAVIS_SOLUTION}
  - bin/test
  - mkdir -v release
  - mkdir -v zip_release
  - cp -v -R GameData release
  - mkdir -p "release/GameData/${PROJECT_NAME}/Plugins"
  - cp -v README.md release
  - cp -v LICENSE release
  - cp -v README.md "release/GameData/${PROJECT_NAME}"
  - cp -v LICENSE "release/GameData/${PROJECT_NAME}"
  - curl 'https://raw.githubusercontent.com/wiki/blowfishpro/B9PartSwitch/Changelog.md' -o '/tmp/B9PartSwitch-Changelog.md'
  - bundle exec extract-changelog -u "$(git describe --tags)" -i '/tmp/B9PartSwitch-Changelog.md' -o "release/GameData/${PROJECT_NAME}/CHANGELOG.md"
  - bundle exec fill-version 'templates/B9PartSwitch.version.erb' 'release/GameData/B9PartSwitch/B9PartSwitch.version'
  - bundle exec rake spec
  - (cd release && zip -v -r ../zip_release/release.zip *)
after_success:
  - mkdir deploy
  - build_script/before_deploy/copy_release.sh
deploy:
  - provider: s3
    skip_cleanup: true
    access_key_id: ${S3_ACCESS_KEY_ID}
    secret_access_key: ${S3_SECRET_ACCESS_KEY}
    bucket: blowfish-ksp-b9partswitch-dev-builds
    storage_class: ONEZONE_IA
    local_dir: deploy/s3/
    upload-dir: builds/${TRAVIS_BRANCH}
    on:
      all_branches: true
      tags: false
  - provider: s3
    skip_cleanup: true
    access_key_id: ${S3_ACCESS_KEY_ID}
    secret_access_key: ${S3_SECRET_ACCESS_KEY}
    bucket: blowfish-ksp-b9partswitch-avc
    local_dir: deploy/avc/
    upload-dir: ksp-${KSP_VERSION}
    on:
      tags: true
  - provider: releases
    skip_cleanup: true
    api_key: ${GITHUB_DEPLOY_TOKEN}
    file: deploy/github/*.zip
    file_glob: true
    name: "${PROJECT_NAME} ${TRAVIS_TAG} for KSP ${KSP_VERSION}"
    on:
      tags: true
env:
  global:
    - PROJECT_NAME='B9PartSwitch'
    - PROJECT_DIR='B9PartSwitch'
    - KSP_VERSION="$(cat KSP_VERSION)"
    - KSP_DLL_PATH="/opt/ksp/assembly/${KSP_VERSION}"
    - PATH="${PATH}:${TRAVIS_BUILD_DIR}/bin"
notifications:
  email: false
git:
  depth: 200
